### ISSUE TITLE
json-cpp 建议换成 rapid-json 或者 nlohmann-json

### ISSUE THREAD

**Issue by X-Crack** [netcan/config-loader#1]
不知是不是作者太过于喜爱 jsoncpp 但2021年以后它过于小众。
既没有 rapid-json 的性能
也没有 nlohmann-json 近乎于接近标准库

性能更是略于 nlohmann-json

**Comment by netcan** [comment]
> 不知是不是作者太过于喜爱 jsoncpp 但2021年以后它过于小众。
> 既没有 rapid-json 的性能
> 也没有 nlohmann-json 近乎于接近标准库
> 
> 性能更是略于 nlohmann-json

`nlohmann-json` 整个git仓拖下来太大了，就放弃了。`rapid-json`我考虑一下。用`jsoncpp`仅仅是无意中看到
