### ISSUE TITLE
对新手菜鸟不友好

### ISSUE THREAD

**Issue by lthcweb** [netcan/config-loader#3]
看了半天，不知道怎么用。
只#include ConfigLoader.h好象不够，需要#include一堆别的东西。
不知道class名是哪个，所以也不知道怎么把ConfigLoader实例化，Test里面也没有。

**Comment by netcan** [comment]
https://github.com/netcan/config-loader/blob/master/test/ut/TinyXML2DeserializeTest.cpp#L17
可以参考这个test。
首先用`DEFINE_STRUCT`定义结构体，然后用`loadXML2Obj`接口提供结构体、xml文件名，之后就能够将xml的内容读到这个结构体中。
